spring:
  application:
    name: telegram-bots

# 配置bots参数
bot:
  proxy:  # 设置网络代理
    host: 127.0.0.1
    port: 8080
    type: SOCKS

  configs:
    - id: xxxx1_Bot
      name: fengge
      token: 123456:AAeReplace39MAJAn1u1s
      consumes:
        - tlg.bot.handler.CommandHandler
        - tlg.bot.handler.UserMessageHandler
      bot-class-name: tlg.busi1.Bot1
      ext-class: eb.busi1.Bot1Extension
      ext-package: eb.busi1

    - id: max_hu_assistant_bot
      name: Mini Assistant
      token: 2424121414:TOKEN_Zq9y3replace84304thisVBA
      consumes:
        - tlg.bot.handler.CommandHandler
        - tlg.bot.handler.UserMessageHandler
      bot-class-name: tlg.bus2.Bot2

logging:
  path: /Users/max/logs
  config: classpath:logback-stdout.xml
  level:
    tlg: INFO
    org.springframework.web.client: WARN
